language: node_js

node_js:
  - 'lts/dubnium'

before_install:
  - npm install --global npm

install:
  - npm clean-install --no-optional

script:
  - npm run build
  - npm test

deploy:
  provider: npm
  email: contact@cichol.com
  api_key:
    secure: Lk9o7yexz/ZoTV9266dzU0WFx67PeZolkImeVMlFrZyhHWjRwWm4bfOrWnq0ZOYWvKtxobfgt6K0BK7CzqQvyQDNIrFmlD8xBUkkYi07Rnw7DOOyciaz3MZIg1uS8OpHtpxTU2TaFZcH5Z4bmqNf/v27tE9pR7Qnrm7WB8QGleNbMPWmqSkXFiRogOEINpDqlJlGuk+AQWsdn8bpM8CfIk4l6FHm2d2o7ywrvb5E/bQePVRRZx4ZVKXym9w7meiSEnbrJHh+u+GHer2lBEBGyRgDkIiN00dWITRfpDV1WfRdHusVztb7VHVWgjOZp4MOpZyYGE7x5Jgl81EGerEszD109+upl10ft72607Q4gTf1HMgQZUJ3jpxDpr4lrkFVk4rHATGyzDQUjb1AMdJPHvc88svOFWIDx7tI27tLMawWFNQggOXlfW0sqFQIpy2W1CLyJhUvkLRdC9dNozd64VBph4nykvo33Uosn+n+8vO6YNyKNN9jdx+KDQqnPm/up7ShmcAMlJyW0vaRMCFhEnVv+dz90Z1vdWeDCb7RoWIhOtyZEX2rE1K3bliGy0DFz0MhbPo3sJNrZsydVO6Ux9JDPfGb/3P0OLlarqKIwV2kPYYgqjvOiwJvpwlGeu0nJsyduWAvPeeldSIW2LC+8aJcNOs3d35DGU+iyiwKgis=
  on:
    tags: true
    repo: epicinium/basis
    branch: master
  skip_cleanup: true
